"""add language to posts

Revision ID: 36091b051f0c
Revises: c59abce2b881
Create Date: 2018-04-04 09:33:30.091721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36091b051f0c'
down_revision = 'c59abce2b881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
